MCQA:
"overfit-brothers/example-mcqa"
"overfit-brothers/krx-textbook"
"overfit-brothers/financial_market_augmented"
"overfit-brothers/TESAT_augmented"
"overfit-brothers/TESAT_augmented-poe-2mask"
"overfit-brothers/TESAT_augmented-poe"
"overfit-brothers/financial_mmlu_augmented"
"overfit-brothers/mmmlu_revised_augmented_cot"
"overfit-brothers/mmmlu_revised_augmented_cot-2mask"
"overfit-brothers/mmmlu_revised_augmented_cot-poe"
"overfit-brothers/account_calc"
instruct:
"overfit-brothers/example-it"
"overfit-brothers/filtered-merged-50k-finqa_quality_filtered"
"overfit-brothers/financial_judgement_instructions"
"overfit-brothers/financial-market-law-it"
"overfit-brothers/jailbreak"